version: "3"
services:
  communication-manager:
    image: communication-manager:latest
    depends_on:
      - kalix-proxy
    ports:
      - "8080:8080"
    environment:
      HOST: communication-manager
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.1.6
    command: -Dconfig.resource=dev-mode.conf -Dlogback.configurationFile=logback-dev-mode.xml -Dkalix.proxy.eventing.support=kafka
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: communication-manager
      USER_FUNCTION_PORT: 8080
      BROKER_CONFIG_FILE: /conf/kafka.properties
      ACL_ENABLED: 'false'
    volumes:
      - ./local.kafka.properties:/conf/kafka.properties

